- hosts: linux
  vars: 
    training:
      topic: ansible
      trainee: sindhu
      lab: aws
  tasks:
  - name: print dist variable
    debug:
      msg: "key is {{  item.key  }} value is {{  item.value  }}"
    with_dict: "{{ training  }}"
